### ISSUE TITLE
i have a json file that combine with a lot of dict? how can i using ijson.items to one by one get dict?

### ISSUE THREAD

**Issue by faker09** [ICRAR/ijson#51] opened 2021-05-13 09:07 UTC

**Comment by rtobar** [comment] 2021-05-13 09:40
@faker09 you'll need to provide more details, otherwise it's nearly impossible to give any advice. Also look if any ijson questions in StackOverflow cover what you need.

**Comment by faker09** [comment] 2021-05-13 12:55
{"datum":{"com.bbn.tc.schema.avro.cdm20.Event":{"uuid":"A.-\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","sequence":null,"type":"EVENT_CREATE_OBJECT","threadId":{"int":3056},"subject":{"com.bbn.tc.schema.avro.cdm20.UUID":"u*N\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"},"predicateObject":{"com.bbn.tc.schema.avro.cdm20.UUID":">\"-\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"},"predicateObjectPath":{"string":"C:\\Users\\admin\\Documents\\Documents"},"predicateObject2":null,"predicateObject2Path":null,"timestampNanos":1557272968456297200,"names":null,"parameters":null,"location":null,"size":null,"programPoint":null,"properties":{"map":{"HasMacro":"4"}}}},"CDMVersion":"20","type":"RECORD_HOST","hostId":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","sessionNumber":0,"source":"SOURCE_WINDOWS_MARPLE"}
{"datum":{"com.bbn.tc.schema.avro.cdm20.Event":{"uuid":"B.-\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","sequence":null,"type":"EVENT_OTHER","threadId":{"int":3056},"subject":{"com.bbn.tc.schema.avro.cdm20.UUID":"u*N\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"},"predicateObject":{"com.bbn.tc.schema.avro.cdm20.UUID":">\"-\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"},"predicateObjectPath":{"string":"C:\\Users\\admin\\Documents\\Documents"},"predicateObject2":null,"predicateObject2Path":null,"timestampNanos":1557272968456415900,"names":{"array":["FileIoClose"]},"parameters":null,"location":null,"size":null,"programPoint":null,"properties":null}},"CDMVersion":"20","type":"RECORD_HOST","hostId":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","sessionNumber":0,"source":"SOURCE_WINDOWS_MARPLE"}
{"datum":{"com.bbn.tc.schema.avro.cdm20.Event":{"uuid":"C.-\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","sequence":null,"type":"EVENT_CREATE_OBJECT","threadId":{"int":3056},"subject":{"com.bbn.tc.schema.avro.cdm20.UUID":"u*N\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"},"predicateObject":{"com.bbn.tc.schema.avro.cdm20.UUID":">\"-\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"},"predicateObjectPath":{"string":"C:\\Users\\admin\\Documents\\Documents"},"predicateObject2":null,"predicateObject2Path":null,"timestampNanos":1557272968456469400,"names":null,"parameters":null,"location":null,"size":null,"programPoint":null,"properties":{"map":{"HasMacro":"4"}}}},"CDMVersion":"20","type":"RECORD_HOST","hostId":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","sessionNumber":0,"source":"SOURCE_WINDOWS_MARPLE"}
{"datum":{"com.bbn.tc.schema.avro.cdm20.Event":{"uuid":"D.-\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","sequence":null,"type":"EVENT_OTHER","threadId":{"int":3056},"subject":{"com.bbn.tc.schema.avro.cdm20.UUID":"u*N\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"},"predicateObject":{"com.bbn.tc.schema.avro.cdm20.UUID":">\"-\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"},"predicateObjectPath":{"string":"C:\\Users\\admin\\Documents\\Documents"},"predicateObject2":null,"predicateObject2Path":null,"timestampNanos":1557272968456604800,"names":{"array":["FileIoClose"]},"parameters":null,"location":null,"size":null,"programPoint":null,"properties":null}},"CDMVersion":"20","type":"RECORD_HOST","hostId":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","sessionNumber":0,"source":"SOURCE_WINDOWS_MARPLE"}
{"datum":{"com.bbn.tc.schema.avro.cdm20.Event":{"uuid":"E.-\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","sequence":null,"type":"EVENT_CREATE_OBJECT","threadId":{"int":3056},"subject":{"com.bbn.tc.schema.avro.cdm20.UUID":"u*N\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"},"predicateObject":{"com.bbn.tc.schema.avro.cdm20.UUID":"b!-\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"},"predicateObjectPath":{"string":"C:\\Users\\admin\\Documents\\Documents\\"},"predicateObject2":null,"predicateObject2Path":null,"timestampNanos":1557272968456686700,"names":null,"parameters":null,"location":null,"size":null,"programPoint":null,"properties":{"map":{"HasMacro":"4"}}}},"CDMVersion":"20","type":"RECORD_HOST","hostId":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","sessionNumber":0,"source":"SOURCE_WINDOWS_MARPLE"}
{"datum":{"com.bbn.tc.schema.avro.cdm20.Event":{"uuid":"F.-\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","sequence":null,"type":"EVENT_OTHER","threadId":{"int":3056},"subject":{"com.bbn.tc.schema.avro.cdm20.UUID":"u*N\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"},"predicateObject":{"com.bbn.tc.schema.avro.cdm20.UUID":"b!-\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"},"predicateObjectPath":{"string":"C:\\Users\\admin\\Documents\\Documents\\"},"predicateObject2":null,"predicateObject2Path":null,"timestampNanos":1557272968456831600,"names":{"array":["FileIoClose"]},"parameters":null,"location":null,"size":null,"programPoint":null,"properties":null}},"CDMVersion":"20","type":"RECORD_HOST","hostId":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","sessionNumber":0,"source":"SOURCE_WINDOWS_MARPLE"}
{"datum":{"com.bbn.tc.schema.avro.cdm20.Event":{"uuid":"G.-\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","sequence":null,"type":"EVENT_CREATE_OBJECT","threadId":{"int":3056},"subject":{"com.bbn.tc.schema.avro.cdm20.UUID":"u*N\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"},"predicateObject":{"com.bbn.tc.schema.avro.cdm20.UUID":"H\"-\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"},"predicateObjectPath":{"string":"C:\\Users\\admin\\Documents"},"predicateObject2":null,"predicateObject2Path":null,"timestampNanos":1557272968456886300,"names":null,"parameters":null,"location":null,"size":null,"programPoint":null,"properties":{"map":{"HasMacro":"4"}}}},"CDMVersion":"20","type":"RECORD_HOST","hostId":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","sessionNumber":0,"source":"SOURCE_WINDOWS_MARPLE"}
{"datum":{"com.bbn.tc.schema.avro.cdm20.Event":{"uuid":"H.-\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","sequence":null,"type":"EVENT_CREATE_OBJECT","threadId":{"int":3056},"subject":{"com.bbn.tc.schema.avro.cdm20.UUID":"u*N\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"},"predicateObject":{"com.bbn.tc.schema.avro.cdm20.UUID":"J\"-\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"},"predicateObjectPath":{"string":"C:\\Users\\admin\\Documents\\"},"predicateObject2":null,"predicateObject2Path":null,"timestampNanos":1557272968456988500,"names":null,"parameters":null,"location":null,"size":null,"programPoint":null,"properties":{"map":{"HasMacro":"4"}}}},"CDMVersion":"20","type":"RECORD_HOST","hostId":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","sessionNumber":0,"source":"SOURCE_WINDOWS_MARPLE"}
{"datum":{"com.bbn.tc.schema.avro.cdm20.Event":{"uuid":"I.-\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","sequence":null,"type":"EVENT_OTHER","threadId":{"int":3056},"subject":{"com.bbn.tc.schema.avro.cdm20.UUID":"u*N\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"},"predicateObject":{"com.bbn.tc.schema.avro.cdm20.UUID":"J\"-\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"},"predicateObjectPath":{"string":"C:\\Users\\admin\\Documents\\"},"predicateObject2":null,"predicateObject2Path":null,"timestampNanos":1557272968457127800,"names":{"array":["FileIoClose"]},"parameters":null,"location":null,"size":null,"programPoint":null,"properties":null}},"CDMVersion":"20","type":"RECORD_HOST","hostId":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","sessionNumber":0,"source":"SOURCE_WINDOWS_MARPLE"}
{"datum":{"com.bbn.tc.schema.avro.cdm20.Event":{"uuid":"J.-\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","sequence":null,"type":"EVENT_CREATE_OBJECT","threadId":{"int":3056},"subject":{"com.bbn.tc.schema.avro.cdm20.UUID":"u*N\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"},"predicateObject":{"com.bbn.tc.schema.avro.cdm20.UUID":"H\"-\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"},"predicateObjectPath":{"string":"C:\\Users\\admin\\Documents"},"predicateObject2":null,"predicateObject2Path":null,"timestampNanos":1557272968457179500,"names":null,"parameters":null,"location":null,"size":null,"programPoint":null,"properties":{"map":{"HasMacro":"4"}}}},"CDMVersion":"20","type":"RECORD_HOST","hostId":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","sessionNumber":0,"source":"SOURCE_WINDOWS_MARPLE"}

**Comment by faker09** [comment] 2021-05-13 13:38
i means that if i use
```
data_json=ijson.items(filename, 'item')
for i in data_json:
      print(i)
```

it don't output anything

**Comment by rtobar** [comment] 2021-05-14 02:03
@faker09 the problem is you are passing ijson the filename instead of a file object. You need to open your file yourself, then give the resulting file object to ijson.

**Comment by faker09** [comment] 2021-05-14 02:20
> @ faker09问题是您要通过ijson传递文件名而不是文件对象。您需要自己打开文件，然后将生成的文件对象提供给ijson。

sorry, i use a confusing parameter name.  actually, i opened a file and pass a file object to ijson.items()

**Comment by rtobar** [comment] 2021-05-14 03:10
@faker09 can you please then provide a cleaner extract of your JSON file? In particular, how does the file start? I get the impression you have a file with multiple top-level JSON objects instead of a single one, in which case you'll need to use an empty prefix and `multiple_values=True` when invoking `ijson.items`. But again, if you provide a cleaner extract of the JSON file (make sure it formats correctly when putting it into the comments here), the code you are using, and any error you might be receiving, it would be better.

**Comment by rtobar** [comment] 2021-05-19 13:05
Closing for lack of clearer explanations.

**Closed by rtobar** 2021-05-19 13:05 UTC
Labels: question
