### ISSUE TITLE
ijson stops to working

### ISSUE THREAD

**Issue by shimonShouei** [ICRAR/ijson#64] opened 2021-12-18 17:44 UTC
Hello, I use this package for a while, and suddenlly it stopped to work.  You can see in the code bellow, it is the seamplest and it doesnt works with any json file. 
when I get to the for loop it doesnt goes in, like the json is empty. And the json is for sure not empty and it worked with ijson before.
My json files is too large to upload.
It is the same in python 3.8 and python 3.6. the ijson is 3.1.4, installed with pip. the beckend is "yajl2". Its the case in both windows and linux.

**The code:**
**_with open(r"G:\.shortcut-targets-by-id\1Zr_v9ggL0ZP7j6DJeTQggwxX7BPmEJ-d\final_project\data\MensRights_2020_.json",_**
          **_'rb') as f:_**
    **_items = ijson.items(f, 'item')_**
    **_for item in items:_**
       **_print(item)_**

Thanks

**Comment by rtobar** [comment] 2021-12-19 01:42
@shimonShouei thanks for resporting an issue. However, without a reproducible example it would be difficult to find out what's going on, and even say for sure ijson is the cause of the problem.

Do you know what changed in your environment that ijson stopped working? Did you move from an older version into a new one? Are your files different? Have you tried to see what happens if you use other backends?

Please provide more details, try to narrow down the causes of the problem, and hopefully provide a reproducible example, otherwise it will be very difficult to diagnose any potential problem.

**Comment by shimonShouei** [comment] 2021-12-19 04:12
Is it working for you? Because as I sayed, it doesn't work in various
environments.

בתאריך יום א׳, 19 בדצמ׳ 2021, 03:42, מאת rtobar ***@***.***>:

**Comment by rtobar** [comment] 2021-12-19 14:41
> Is it working for you? Because as I sayed, it doesn't work in various environments.

As indicated in my previous comment, without further details I can't really tell what's happening. I can't say 'it worked for me" or not if you don't provide a reproducible example with an explanation of what your error is.

The only thing I can think of is that your JSON documents don't match your expectations, so the prefix you are using for the `items` function doesn't produce any objects.

**Comment by rtobar** [comment] 2021-12-26 13:44
It's been 7 days since the original report and no more information about this. I'm closing this for the moment, but we can re-open if more information is provided.

**Closed by rtobar** 2021-12-26 13:44 UTC
Labels: bug
