### ISSUE TITLE
errors in python and yajl2_c backends

### ISSUE THREAD

**Issue by Bubu** [ICRAR/ijson#45] opened 2021-03-19 14:55 UTC
I've hit another snag with my libarchive experiment:

(Currently using https://github.com/smartfile/python-libarchive, working with this file-like object: https://github.com/smartfile/python-libarchive/blob/master/libarchive/__init__.py#L183)

When using either the `python` or the `yajl2_c` backends I hit some error condition on the end of the file. It works correctly with the `yajl2_cffi` or `yajl2` backends.

Here's what happens when using `yajl2_c`:
```
count = 0
with libarchive.Archive('myarchive.zip') as archive:
    for entry in archive:
        if entry.pathname == 'myjson.json':

            jsonstream = archive.readstream(entry.size)
            objects = ijson.items(jsonstream, 'somekey.item')
            for o in objects:
                count +=1
                print(count)
```
```
[prints the correct number of things, so everything is parsed right to the end it seems]
Traceback (most recent call last):
  File "myfile.py", line 60, in <module>
    for o in objects:
TypeError: a bytes-like object is required, not 'NoneType'
```
With the python backend (same code):
```
[same correct number again]
Traceback (most recent call last):
  File myfile.py", line 60, in <module>
    for o in objects:
  File "/usr/lib/python3.9/site-packages/ijson/utils.py", line 55, in coros2gen
    f.send(value)
  File "/usr/lib/python3.9/site-packages/ijson/backends/python.py", line 36, in utf8_encoder
    sdata = decode(bdata, final)
  File "/usr/lib/python3.9/codecs.py", line 321, in decode
    data = self.buffer + input
TypeError: can't concat NoneType to bytes
```

I'm not sure if I'm doing something wrong with calling ijson, or that my file-stream from libarchive is somehow "weird" (but I wouldn't know how really). The weird thing is that it works with the cffi backend. Oh and it also works with all backends if I `.read()` the full jsonstream into memory (but this defeats the point of using ijson of course).

**Comment by rtobar** [comment] 2021-03-19 23:32
@Bubu thanks again for getting in touch and the details in the report.

The problem is exactly one that you suspect: your file-object from `libarchive` is "weird" in the sense that when it gets to the endof the file it implicitly returns `None` instead of an empty string ([here](https://github.com/smartfile/python-libarchive/blob/master/libarchive/__init__.py#L214) and [here](https://github.com/smartfile/python-libarchive/blob/master/libarchive/__init__.py#L217)). File-like objects are expected to return an empty string (`''` or `b''`, depending on the mode with which it operates) when the end of the file is reached. This is the behavior that ijson expects as well, although clearly different backends are more or less strict about this (some do something like `if not buffer`, in which case `None` just works, but others are not that lenient), which is why some fail and some others don't.

I'd say this is not a bug on our end, but something that will need to be corrected in `python-libarchive`. In the meanwhile you'll have to wrap their `EntryReadStream` class into your own and provide the `None` -> `b''` conversion yourself if you want to continue down that route.

Based on this, I'll mark this issue as "invalid" and will close it, but I'm happy to continue the discussion if needed.

**Closed by rtobar** 2021-03-19 23:32 UTC

**Comment by Bubu** [comment] 2021-03-20 12:38
Thanks for the detailed explanation. I'll see about opening an issue with python-libarchive.
