### ISSUE TITLE
Ijson 3.1.2 causing Segmentation fault.

### ISSUE THREAD

**Issue by ahmedwael** [ICRAR/ijson#66] opened 2021-12-22 13:55 UTC
When updating from v3.1.1 to v3.1.2 we experienced segmentation fault errors. I noticed in the changelog that the changes were addressing memory leaks and it affected all generators, including 'parse'.

In our code, we receive data in the form of json. We turn it to a json file as follows: 

```
def write_response_to_local_file(self, response, file):
        with open(file, 'wb') as f:
            shutil.copyfileobj(response.raw, f)
```

and then we parse the json file as follows (I simplified the parse_data function to avoid unnecessary details, the point is to show that as we parse through json_stream, we either continue, yield, break or pass.

```
    def get_results(self):
        with open(self.filename) as file:
            json_stream = ijson.parse(file)
            for results in self.parse_data(json_stream):
                yield results

    def parse_data(self, json_stream):
        results = self.create_accumulator()
        for prefix, the_type, value in json_stream:
            if self.stop_parsing_stream(prefix):
                break
            if self.dates_in_dimensions:
                 results_for_period = self.handle_entries_depth(results_for_period)
             yield results
             try:
                 results_for_period = self.depth_handlers[current_depth](results_for_period)
             except KeyError:
                 pass
             self.update_accumulator(the_type, value)
             continue
```

Our workflow runs via many 'workers' that are all grabbing jobs from a redis queue. The job includes fetching data via http request in json format, and parsing it. Out of ~10K redis jobs, ~100 would generate a seg. fault and the failed jobs would be requeued. On the second attempt, ~5 of those requeued jobs will fail, and on third attempt usually one job will again fail with a seg. fault. The behavior is not deterministic, i.e. rerunning the same workflow instance doesn't reproduce the same jobs to fail. Therefore I am not able to get an obvious reproducer.

In case it helps, our json responses tend to look something like this:

```
{
    "Dimensions": {
        "Id": [
            "000.j"
        ],
        "F": [
            "a",
	    "b"
        ],
        "P": [
            "1995y",
            "1996y"
        ],
        "D": [
            20191027
        ],
        "A": [
            "x",
            "y"
        ]
    },
    "Data": [
        [
            [
                300.1,
                3
            ],
            [
                400.1,
                3
            ]
        ],
		[
            [
                500.1,
                3
            ],
            [
                600.1,
                3
            ]
        ]
	]
}
```

**Comment by rtobar** [comment] 2021-12-22 14:18
@ahmedwael thank you very much for reporting this.

Although there'sba fair amount of detail already in there, I think it's a bit insufficient to make a guess about what's going on. More details would help, like a backtrace, information on the environment (OS, python version), and most definitely if you could provide an easy to reproduce example.

It looks like you are almost there with the code excerpt and sample JSON document, but if you could take it a step further and make it reproducible it would make it possible for me to find out what's going on.

**Comment by rtobar** [comment] 2022-03-08 08:10
@ahmedwael any chance you can try this out? Otherwise I'll merge to the `master` branch without your feedback.

**Comment by rtobar** [comment] 2022-03-16 01:58
No feedback provided, fix merged to the `master` anyway.

**Closed by rtobar** 2022-03-16 01:58 UTC
Labels: bug, Needs more information
